#!/bin/bash

# Assignment #12 execution timing script.
#
# -----------------------------------------------------
# Initial checks.
#	Ensure executable files exists.
#	Ensure test file exists
#
if [ -z $1 ]; then
	echo "Usage:  ./a12timer <asst12_Executable>"
	exit
fi
#
if [ ! -e $1 ] || [ ! -x $1 ]; then
	echo "Error, unable to find assignment #12 $1 executable file."
	exit
fi
#
# -----------------------------------------------------
# Display cute header
#
bolded=`tput bold`
normal=`tput sgr0`
#
clear
echo "**********************************************"
echo -e "${bolded}Assignment #12 -> Timed Executions${normal}"
echo -e "This will take a few minutes...\n\n"
#
# -----------------------------------------------------
#  Times tests
#
echo "##############################################" > a12times.txt
echo "##############################################" > a12results.txt
echo -e "Starting Timed Executions\\n"
#
for cnt in {1..4..1}
do
	echo -e "\\n-------------------" >> a12times.txt
	echo -e "\\n-------------------" >> a12results.txt
	echo "Timed Test ($cnt thread)" >> a12times.txt
	echo "Timed Test ($cnt thread)" >> a12results.txt
	(time ./$1 -t $cnt -l 1023252) >> a12results.txt 2>> a12times.txt
	echo "Timed Test ($cnt thread) completed."
done
#
echo  >> a12times.txt
echo  >> a12times.txt
#
#
# -----------------------------------------------------
# Done
#
echo
echo
echo "Timed Tests completed."
echo "See ${bolded}a12times.txt${normal} and ${bolded}a12resuls.txt${normal} for results "
echo

